package in.bigdash.rms.model.request;


public enum RequestStatus {

    OPEN,
    ASSIGNED,
    INPROGRESS,
    FETCHED,
    PACKED,
    ASSIGNED_RETRIEVAL_DESK,
    ASSIGNED_LOGISTICS_DESK,
    ASSIGNED_DELIVERY,
    ASSIGNED_DESTRUCTION_DESK,
    ASSIGNED_RACK_MANAGEMENT,
    RESTORING,
    TRANSIT,
    INCOMING,
    VALIDATED,
    STORED,
    HOLDINGBAY,
    SIGNOFF,
    DELIVERED,
    DESTROYING,
    DESTROYED,
    INSERTED,
    CLOSED,
    CANCELLED
}
