package in.bigdash.rms.model.request;


public enum RequestStatus {

    OPEN, ASSIGNED, INPROGRESS, PACKED, TRANSIT, INCOMING, VALIDATED, STORED, HOLDINGBAY, SIGNOFF, DELIVERED, SHREDDING, INSERTED, CLOSED, CANCELED
}
