alter table bdrms.bd_box drop foreign key FK2c5yx4s3qvqq0yfajqwme1xs6;
alter table bdrms.bd_box_aud drop foreign key FKhfaxfkiwx2hiiv8tlg3kjho5g;
alter table bdrms.bd_client_aud drop foreign key FK2fdloexke73q36vssvfopqie1;
alter table bdrms.bd_client_storage_types drop foreign key FKqk8xhr1ffjm7whu4m7qa3hfig;
alter table bdrms.bd_client_storage_types drop foreign key FKpx5h8g2wte6uv26it3lporwo0;
alter table bdrms.bd_document drop foreign key FKp8srkf4cdye0my6g3wtt91ewc;
alter table bdrms.bd_document_aud drop foreign key FKavr6a3lwmbs5rfv8guf0gq9wm;
alter table bdrms.bd_facility_aud drop foreign key FKfaasw5xnwp7g6dklhhsebs0et;
alter table bdrms.bd_file drop foreign key FKfnd5cvn305i0wdmcmpxx7cntd;
alter table bdrms.bd_file_aud drop foreign key FKpictog8ebyyclvj7cvumsju24;
alter table bdrms.bd_inventory_item drop foreign key FKs09xae4h9cgkyyc4tksesoueu;
alter table bdrms.bd_inventory_item drop foreign key FKkwjfso49y9isuev1on6kuonkn;
alter table bdrms.bd_inventory_item drop foreign key FKfv10n2g5elpapyohn06lsl0hf;
alter table bdrms.bd_inventory_item drop foreign key FKqo1svkky77g75moxwuy0rph1l;
alter table bdrms.bd_inventory_item_aud drop foreign key FKhqb252dcpuwxgrvhnly68enht;
alter table bdrms.bd_request drop foreign key FKsp8r0x8d7ej0625dy4bs9yq3r;
alter table bdrms.bd_request drop foreign key FKict2oflenkawn24fi1ox0r8l2;
alter table bdrms.bd_request drop foreign key FK6g2bp6wogl38yvigi9cwp7gqc;
alter table bdrms.bd_request_aud drop foreign key FKql71vklb6ft68f3hbk9f3h17r;
alter table bdrms.bd_request_inventory_item drop foreign key FKnv9tsx3mioj1jd5qabv375r58;
alter table bdrms.bd_request_inventory_item drop foreign key FKo5kj0epb8uw3ylqfy7kfvkl7l;
alter table bdrms.bd_shelf drop foreign key FK12tmyh5foeoo00cdlgnyts7jd;
alter table bdrms.bd_shelf_aud drop foreign key FKdb6rak799xdmdfi1ijru18qt2;
alter table bdrms.bd_user drop foreign key FK8odu6j33wu0o3l8bso8wqhw7e;
alter table bdrms.bd_user_aud drop foreign key FKajhmkayj0k4kmp1gymgrvokog;
alter table bdrms.bd_user_role drop foreign key FK82p0x0e47k911rkyfxt2kemah;
alter table bdrms.bd_user_role drop foreign key FKkg5qwik6m3pju9evn44kv6kjg;
drop table if exists bdrms.bd_box;
drop table if exists bdrms.bd_box_aud;
drop table if exists bdrms.bd_client;
drop table if exists bdrms.bd_client_aud;
drop table if exists bdrms.bd_client_storage_types;
drop table if exists bdrms.bd_document;
drop table if exists bdrms.bd_document_aud;
drop table if exists bdrms.bd_facility;
drop table if exists bdrms.bd_facility_aud;
drop table if exists bdrms.bd_file;
drop table if exists bdrms.bd_file_aud;
drop table if exists bdrms.bd_inventory_item;
drop table if exists bdrms.bd_inventory_item_aud;
drop table if exists bdrms.bd_request;
drop table if exists bdrms.bd_request_aud;
drop table if exists bdrms.bd_request_inventory_item;
drop table if exists bdrms.bd_role;
drop table if exists bdrms.bd_shelf;
drop table if exists bdrms.bd_shelf_aud;
drop table if exists bdrms.bd_storage_type;
drop table if exists bdrms.bd_user;
drop table if exists bdrms.bd_user_aud;
drop table if exists bdrms.bd_user_role;
drop table if exists bdrms.revinfo;
